{{- if and (eq (include "common.tls.require-secure-inter" $) "true") (not .Values.certificateResources.tlsSecretName) (not .Values.certificateResources.jksPasswordSecretName) }}

{{- $component := "data-store" -}}
{{- $secretName := (printf "%s-jks" (include "data-store.name" $)) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName | quote }}
  namespace: {{ (include "common.names.namespace" .) | quote }}
  labels: {{ include "common.labels.standard" (dict "name" (include "data-store.name" .) "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: {{ $component | quote }}
    {{ include "common.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    {{ include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
type: Opaque
data:
  jks-password: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" "jks-password" "providedValues" (list) "length" 10 "strong" true "context" $) }}

{{- end }}