{{- $component := "data-store" -}}
{{- $name := (printf "%s-statefulset" (include "data-store.name" $)) -}}
{{- $secureOnlyPorts := false -}}
{{- $extraVolMounts := default list .Values.extraVolumeMounts -}}
{{- $extraVols := default list .Values.extraVolumes -}}

{{- if eq (include "common.tls.require-secure-inter" .) "true" -}}
  {{- $secureOnlyPorts = true -}}
  {{- $tlsSecretName := coalesce .Values.certificateResources.tlsSecretName (printf "%s-tls" (include "data-store.name" .)) -}}
  {{- $jksPassSecretName := coalesce .Values.certificateResources.jksPasswordSecretName (printf "%s-jks" (include "data-store.name" .)) -}}

  {{- $extraVolMounts = append $extraVolMounts (include "common.tls.volumeMounts.certs" . | fromJson) -}}
  {{- $extraVolMounts = append $extraVolMounts (include "common.tls.volumeMounts.jks" . | fromJson) -}}

  {{- $extraVols = append $extraVols (include "common.tls.volumes.certs" (dict "tlsSecretName" $tlsSecretName "context" $) | fromJson) -}}
  {{- $extraVols = append $extraVols (include "common.tls.volumes.jks-store" (dict "jksPasswordSecretName" $jksPassSecretName "tlsSecretName" $tlsSecretName "context" $) | fromJson) -}}
{{- end -}}

{{/*
Todo: the readiness probe is assusming the admin server is enabled. For now it gets disabled if the server is disabled. It should change over to "/pulsar/bin/bookkeeper shell bookiesanity"
*/}}
{{- if .Values.config.httpServerEnabled -}}
  {{- $_ := set .Values.readinessProbe.httpGet "port" .Values.config.httpServerPort -}}
{{- else -}}
  {{- $_ := set .Values.readinessProbe "enabled" false  -}}
{{- end -}}

apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ $name | quote }}
  namespace: {{ (include "common.names.namespace" .) | quote }}
  labels: {{ include "common.labels.standard" (dict "name" (include "data-store.name" $) "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: {{ $component | quote }}
    {{ include "common.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    {{ include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
spec:
  podManagementPolicy: {{ .Values.podManagementPolicy | quote }}
  replicas: {{ int .Values.replicas }}
  selector:
    matchLabels: {{ (include "common.labels.matchLabels" (dict "name" (include "data-store.name" $) "context" $ )) | nindent 6 }}
      app.kubernetes.io/component: {{ $component | quote }}
  serviceName: {{ printf "%s-headless" (include "data-store.name" .) }}
  updateStrategy: {{ include "common.tplvalues.render" (dict "value" .Values.updateStrategy "context" $ ) | nindent 4 }}
  template:
    metadata:
      labels: {{ include "common.labels.standard" (dict "name" (include "data-store.name" .) "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: {{ $component | quote }}
        {{- if .Values.podLabels }}
        {{ include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
      annotations:
        checksum/configuration: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{ include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.hostAliases }}
      hostAliases: {{ include "common.tplvalues.render" (dict "value" .Values.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      hostIPC: {{ .Values.hostIPC }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName | quote }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{ include "common.tplvalues.render" (dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{ include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "component" $component "name" $name "extraMatchLabels" (dict) "context" $) | nindent 10}}
        podAntiAffinity: {{ include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "component" $component "name" $name "extraMatchLabels" (dict) "context" $) | nindent 10 }}
        nodeAffinity: {{ include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ include "common.tplvalues.render" (dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{ include "common.tplvalues.render" (dict "value" .Values.topologySpreadConstraints "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{ omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "data-store.serviceAccountName" . }}
      initContainers: {{ include "common.lifeCycle.meta-data-store-running" . | nindent 8 }}
      {{- if .Values.initContainers }}
        {{ include "common.tplvalues.render" ( dict "value" .Values.initContainers "context" $ ) | nindent 8 }}
      {{- end }}
      containers:
        - name: data-store
          image: {{ include "common.images.image" (dict "imageRoot" .Values.image "global" .Values.global) }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{ include "common.images.renderPullSecrets" ( dict "images" (list .Values.image) "context" $) }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{ omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.containerCommand }}
          command:
            {{ include "common.tplvalues.render" (dict "value" .Values.containerCommand "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.containerArgs }}
          args:
            {{ include "common.tplvalues.render" (dict "value" .Values.containerArgs "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.extraEnvVars }}
            {{ include "common.tplvalues.render" ( dict "value" .Values.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if or .Values.extraEnvVarsCM .Values.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- end }}
          ports:
            {{- if and (eq (include "common.tls.require-secure-inter" .) "false") .Values.containerPorts.client}}
            - name: client
              containerPort: {{ .Values.containerPorts.client }}
            {{- end -}}
            {{- if and (eq (include "common.tls.require-secure-inter" .) "true") .Values.containerPorts.clientTls}}
            - name: client-tls
              containerPort: {{ .Values.containerPorts.clientTls }}
            {{- end -}}
            {{- if and (eq (include "data-store.stateStoreEnabled" .) "true") .Values.containerPorts.stateStorage}}
            - name: state-storage
              containerPort: {{ .Values.containerPorts.stateStorage }}
            {{- end -}}
            {{- if and .Values.config.httpServerEnabled .Values.config.httpServerPort}}
            - name: http
              containerPort: {{ .Values.config.httpServerPort }}
            {{- end -}}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe: {{ include "common.tplvalues.render" (dict "value" (omit .Values.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe: {{ include "common.tplvalues.render" (dict "value" (omit .Values.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe: {{ include "common.tplvalues.render" (dict "value" (omit .Values.startupProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.lifecycleHooks }}
          lifecycle: {{ include "common.tplvalues.render" (dict "value" .Values.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.resources }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: "logs"
              mountPath: {{ .Values.logPersistence.mountPath }}
            - name: "conf"
              mountPath: {{ .Values.pulsarEnv.confPath }}
            {{- if eq .Values.persistence.oneDisk.enabled true }}
            - name: oneDisk
              mountPath: {{ .Values.persistence.oneDisk.mountPath }}
            {{- else }}
            - name: journal
              mountPath: {{ .Values.persistence.journal.mountPath }}
            - name: ledgers
              mountPath: {{ .Values.persistence.ledgers.mountPath }}
            {{- if eq (include "data-store.stateStoreEnabled" .) "true" }}
            - name: ranges
              mountPath: {{ .Values.persistence.ranges.mountPath }}
            {{- end }}
            {{- end }}
            {{- if $extraVolMounts }}
            {{ include "common.tplvalues.render" (dict "value" $extraVolMounts "context" $) | nindent 12 }}
            {{- end }}
        {{- if .Values.sidecars }}
        {{ include "common.tplvalues.render" (dict "value" .Values.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.logPersistence.existingClaim }}
        - name: "logs"
          persistentVolumeClaim:
            claimName: {{ printf "%s" (tpl .Values.logPersistence.existingClaim .) }}
        {{- end }}
        - name: "conf"
          configMap:
            name: {{ printf "%s-configuration" (include "data-store.name" .) }}
        {{- if eq .Values.persistence.enabled false }}
        {{- if eq .Values.persistence.oneDisk.enabled true }}
        - name: oneDisk
          emptyDir: {}
        {{- else }}
        - name: journal
          emptyDir: {}
        - name: ledgers
          emptyDir: {}
        {{- if eq (include "data-store.stateStoreEnabled" .) "true" }}
        - name: ranges
          emptyDir: {}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if $extraVols }}
        {{ include "common.tplvalues.render" (dict "value" $extraVols "context" $) | nindent 8 }}
        {{- end }}
{{- if eq .Values.persistence.enabled true }}
  volumeClaimTemplates:
{{- end }}
{{- if not .Values.logPersistence.existingClaim }}
    - metadata:
        name: "logs"
        {{- if .Values.logPersistence.annotations }}
        annotations: {{ include "common.tplvalues.render" (dict "value" .Values.logPersistence.annotations "context" $) | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.logPersistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.logPersistence.size | quote }}
        {{- include "data-store.logPersistence.storageClass" . | nindent 8 }}
        {{- if .Values.logPersistence.selector }}
        selector: {{- include "common.tplvalues.render" (dict "value" .Values.logPersistence.selector "context" $) | nindent 10 }}
        {{- end }}
{{- end }}
{{- if eq .Values.persistence.enabled true }}
  {{- if and (eq .Values.persistence.oneDisk.enabled true) (not .Values.persistence.oneDisk.existingClaim) }}
    - metadata:
        name: oneDisk
        {{- if .Values.persistence.oneDisk.annotations }}
        annotations: {{ include "common.tplvalues.render" (dict "value" .Values.persistence.oneDisk.annotations "context" $) | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.oneDisk.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.oneDisk.size | quote }}
        {{ include "data-store.persistence.oneDisk.storageClass" . | nindent 8 }}
        {{- if .Values.persistence.oneDisk.selector }}
        selector: {{ include "common.tplvalues.render" (dict "value" .Values.persistence.oneDisk.selector "context" $) | nindent 10 }}
        {{- end }}
  {{- else }}
    {{- if not .Values.persistence.journal.existingClaim }}
    - metadata:
        name: journal
        {{- if .Values.persistence.journal.annotations }}
        annotations: {{ include "common.tplvalues.render" (dict "value" .Values.persistence.journal.annotations "context" $) | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.journal.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.journal.size | quote }}
        {{ include "data-store.persistence.journal.storageClass" . | nindent 8 }}
        {{- if .Values.persistence.journal.selector }}
        selector: {{ include "common.tplvalues.render" (dict "value" .Values.persistence.journal.selector "context" $) | nindent 10 }}
        {{- end }}
    {{- end }}
    {{- if not .Values.persistence.ledgers.existingClaim }}
    - metadata:
        name: ledgers
        {{- if .Values.persistence.ledgers.annotations }}
        annotations: {{ include "common.tplvalues.render" (dict "value" .Values.persistence.ledgers.annotations "context" $) | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.ledgers.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.ledgers.size | quote }}
        {{ include "data-store.persistence.ledgers.storageClass" . | nindent 8 }}
        {{- if .Values.persistence.ledgers.selector }}
        selector: {{ include "common.tplvalues.render" (dict "value" .Values.persistence.ledgers.selector "context" $) | nindent 10 }}
        {{- end }}
    {{- end }}
    {{- if and (eq (include "data-store.stateStoreEnabled" .) "true") (not .Values.persistence.ranges.existingClaim) }}
    - metadata:
        name: ranges
        {{- if .Values.persistence.ranges.annotations }}
        annotations: {{ include "common.tplvalues.render" (dict "value" .Values.persistence.ranges.annotations "context" $) | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
        {{- range .Values.persistence.ranges.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.ranges.size | quote }}
        {{ include "data-store.persistence.ranges.storageClass" . | nindent 8 }}
        {{- if .Values.persistence.ranges.selector }}
        selector: {{ include "common.tplvalues.render" (dict "value" .Values.persistence.ranges.selector "context" $) | nindent 10 }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}