{{- $component := "life-cycle" -}}
{{- $name := "meta-data-store-running" -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name | quote }}
  namespace: {{ (include "common.names.namespace" .) | quote }}
  labels: {{ include "common.labels.standard" (dict "name" (include "meta-data-store.name" $) "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: {{ $component | quote }}
    {{ include "common.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    {{ include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
spec:
  backoffLimit: 5
  template:
    metadata:
      name: {{ $name | quote }}
      labels: {{ include "common.labels.standard" (dict "name" $component "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: {{ $component | quote }}
    spec:
      restartPolicy: Never
      containers:
        - name: wait-for-meta-data-initialize
          image: groundnuty/k8s-wait-for:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: WAIT_TIME
              value: "5"
            - name: DEBUG
              value: "1"
          args:
            - "job"
            - {{ (printf "%s-initialize-cluster-meta-data" (include "meta-data-store.name" $)) | quote }}
