{{- if and (eq (include "common.tls.require-secure-inter" $) "true")
          (not .Values.certificateResources.tlsSecretName)
          (not .Values.certificateResources.jksPasswordSecretName)
          (not .Values.global.interComponentTls.jksPasswordSecretName) }}

{{- $component := "metadata-store" -}}
{{- $name := (printf "%s-jks" (include "metadata-store.name" $)) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $name | quote }}
  namespace: {{ (include "common.names.namespace" .) | quote }}
  labels: {{ include "common.labels.standard" (dict "name" (include "metadata-store.name" .) "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: {{ $component | quote }}
    {{ include "common.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    {{ include "common.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
type: Opaque
data:
  jks-password: {{ include "common.secrets.passwords.manage" (dict "secret" $name "key" "jks-password" "providedValues" (list) "length" 20 "strong" true "context" $) }}

{{- end }}