apiVersion: v2
description: Apache Pulsar Helm chart for Kubernetes
name: apache-pulsar
version: "0.1.0"
appVersion: "0.1.0"
type: application
maintainers:
  - name: David Dieruf
    email: david@dierufventures.com
dependencies:
  - name: common
    version: "0.1.0"

  - name: meta-data-store
    version: "0.1.0"
    alias: metaDataStore
    import-values:
      - child: globalData
        parent: global.metaDataStore
      - child: config
        parent: global.metaDataStore.config
      - child: service
        parent: global.metaDataStore.service

  - name: data-store
    version: "0.1.0"
    alias: dataStore
    import-values:
      - child: globalData
        parent: global.dataStore
      - child: config
        parent: global.dataStore.config

  - name: broker
    version: "0.1.0"
    import-values:
      - child: globalData
        parent: global.broker
      - child: config
        parent: global.broker.config
      - child: service
        parent: global.broker.service