## @section Pulsar global settings
## @descriptionStart
## These are global values that all sub charts will inherit
## @descriptionEnd
##
global:

  image:

    ## @param global.image.registry [string,nullable] The image registry used by all charts
    ##
    registry: "docker.io"

    ## @param image.repository [string,nullable] Component image repository
    ##
    repository: "datastax/lunastreaming"

    ## @param image.tag [string,nullable] Component image tag (immutable tags are recommended)
    ##
    tag: "2.10_2.3"

    ## @param image.pullPolicy Component image pull policy
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent

    ## @param image.pullSecrets [array,nullable] Specify docker-registry secret names as an array
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: [ ]

  ## @param global.storageClass [string,nullable] The storage class used by all sub charts when using persistence.
  ##
  storageClass:

  ## @param global.kubeVersion [string,nullable] Override Kubernetes version
  ##
  kubeVersion: ""

  ## @param global.clusterDomain [string,nullable] Default Kubernetes cluster domain
  ##
  clusterDomain: cluster.local

  ## @param global.namespaceOverride [string,nullable] Override the release namespace
  ##
  namespaceOverride: ""

  ## @param global.commonLabels [array,nullable] Labels to add to all deployed objects
  ##
  commonLabels:
    app.kubernetes.io/part-of: apache-pulsar

  ## @param global.commonAnnotations [object,nullable] Annotations to add to all deployed objects
  ##
  commonAnnotations: {}

  ## @param global.secureClusterEdge Only allow secure ports to be opened at the edge of the Pulsar cluster (also force TLS in all ingresses)
  ##
  secureClusterEdge: false

  interComponentTls:

    ## @param global.interComponentTls.enabled Only allow communication over secure ports between all cluster components
    ##
    enabled: false

    ## @param  global.interComponentTls.tlsSecretName [string,nullable] The name of an existing tls secret that includes a JKS store
    ##
    tlsSecretName:

    ## @param  global.interComponentTls.jksPasswordSecretName [string,nullable] The name of the secret used to create the JKS store in an existing tls secret
    ##
    jksPasswordSecretName:

    ## @param global.interComponentTls.issuerRef [object,nullable] IssuerRef is a reference to the issuer of all certificates. Note that each component can have their own issuerRef that overrides this.
    ##
    issuerRef:
      name:
      kind:

  ## @section Observability
  ## @descriptionStart
  ## Values related to enabling or disabling metrics endpoints and pre-configured dashboards. Note these values override an individual component's metrics settings.
  ## Read more in the [chart wiki](https://github.com/ddieruf/apache-pulsar-helm-chart/wiki)
  ## @descriptionEnd
  ##
  observability:

    ## @param global.observability.serviceMonitors Globally enable all components' metrics scraping by creating service monitors that are discoverable by Prometheus.
    ##
    serviceMonitors: true

    ## @param global.observability.dashboards Deploy configmaps with pre-configured dashboards that are discoverable by Grafana.
    ##
    dashboards: true

  ## @section Tenant, Namespace, and Topic Setup
  ## @descriptionStart
  ## Specify the initial tenant/namespace/topics created. lobal.pulsarCluster.name is required but tenants, namespaces, and topics are all optional.
  ## @descriptionEnd
  ## Example:
  ##  pulsarCluster:
  ##    name: "my-cluster"
  ##    tenants:
  ##      - name: "public"
  ##        namespaces:
  ##          - name: "default"
  ##      - name: "sample-tenant"
  ##        namespaces:
  ##          - name: "some-namespace"
  ##            topics:
  ##              - name: "first"
  ##                persistent: true
  ##              - name: "second"
  ##                persistent: false
  ##
  pulsarCluster:

    ## @param global.pulsarCluster.name The required name of the Pulsar cluster
    ##
    name: "pulsar-cluster-1"