name: Ping Command

on:
  workflow_call:
    inputs:
      sender-login:
        required: false
        type: string
      repository:
        required: false
        type: string
      comment-id:
        required: false
        type: string
    secrets:
      BOT_ACTION_TOKEN:
        required: false

jobs:
  PingCommand:
    permissions:
      issues: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Add pong in comment
        if: inputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BOT_ACTION_TOKEN }}
          repository: ${{inputs.repository }}
          comment-id: ${{ inputs.comment-id }}
          reaction-type: hooray
          body: |
            > Hi @${{ inputs.sender-login }}. Pong.

      - name: Echo pong
        if: inputs.comment-id == ''
        run: echo "Hi @${{ inputs.sender-login }}. Pong."